# This file was generated by GoReleaser. DO NOT EDIT.
cask "autozeagent" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "3d596573ebb8b1ab42e44954ec711cc4a617817dcfe941aa8cea205554f63f5d"
      url "https://github.com/yyZe0122/AutoZeAgent/releases/download/v#{version}/autozeagent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0533ed6f142df6b5d56c46aecaa20be230c9399c01b34b5f9b64980b861eed97"
      url "https://github.com/yyZe0122/AutoZeAgent/releases/download/v#{version}/autozeagent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c9999a6a2f569f1510f2dd0830a56b9238362e31a4fec6b87a8755f1d38756ef"
      url "https://github.com/yyZe0122/AutoZeAgent/releases/download/v#{version}/autozeagent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e2b5434e68070e7b47fc9221a4416274103dbc6f9914dd0e54d94160e65b02e7"
      url "https://github.com/yyZe0122/AutoZeAgent/releases/download/v#{version}/autozeagent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "autozeagent"
  desc "Local-first, policy-controlled automation agent"
  homepage "https://github.com/yyZe0122/AutoZeAgent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "autozeagent"
  binary "autozeagentd"
  binary "aze"

  # No zap stanza required

end
