# This file was generated by GoReleaser. DO NOT EDIT.
cask "ymz" do
  version "0.2.6"

  on_macos do
    on_intel do
      sha256 "edb0a6e14477161a37b5eb639b3a7fe9d92c185795c4a59ef780b46d15e2019e"
      url "https://github.com/yyZe0122/YunmengZe-Agent/releases/download/v#{version}/ymz_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f7ce8d0dbfb68bd05a48b4075d63319f475f56452b9595c11072777aa604bbdc"
      url "https://github.com/yyZe0122/YunmengZe-Agent/releases/download/v#{version}/ymz_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4e89cc3c3018b05693d8bd60a123851826a7c93a9b8f390bad287b826efc1e50"
      url "https://github.com/yyZe0122/YunmengZe-Agent/releases/download/v#{version}/ymz_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "945ac139203f4045dc68200aa3029113914a5133fcfdc9dff10ee9ff36b67f4c"
      url "https://github.com/yyZe0122/YunmengZe-Agent/releases/download/v#{version}/ymz_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ymz"
  desc "YunmengZe Agent — local-first, policy-controlled automation agent"
  homepage "https://github.com/yyZe0122/YunmengZe-Agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ymz"
  binary "ymzd"

  # No zap stanza required

end
