# This file was generated by GoReleaser. DO NOT EDIT.
cask "ymz" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "0bb1f78a22001564f143b8dc8902654d0413fb73001eb3ea1373583c4d954902"
      url "https://github.com/yyZe0122/YunmengZe-Agent/releases/download/v#{version}/ymz_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f8771d330b28a51a0e7e89de283d5c4dbba9ace228c583699d90032da2d82210"
      url "https://github.com/yyZe0122/YunmengZe-Agent/releases/download/v#{version}/ymz_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ea682b0c84aecb310d6c25a98feac00f93d4a5ae9498ab5e6f716072052c53d7"
      url "https://github.com/yyZe0122/YunmengZe-Agent/releases/download/v#{version}/ymz_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "07b0331cfa2645824094aaf0085a9041a781a1cd6ad0e64321fb6dde09d59ec5"
      url "https://github.com/yyZe0122/YunmengZe-Agent/releases/download/v#{version}/ymz_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ymz"
  desc "YunmengZe Agent — local-first, policy-controlled automation agent"
  homepage "https://github.com/yyZe0122/YunmengZe-Agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ymz"
  binary "ymzd"

  # No zap stanza required

end
