# This file was generated by GoReleaser. DO NOT EDIT.
cask "ymz" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "daed28e88cfd2a651a2680b6fa9e3ac95c9425662833c5d8a1e72c89456ffd4b"
      url "https://github.com/yyZe0122/YunmengZe-Agent/releases/download/v#{version}/ymz_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "60887ec59ee1eb5bfff33a355630e4b7d17e281605b00c28839e958cd6d26439"
      url "https://github.com/yyZe0122/YunmengZe-Agent/releases/download/v#{version}/ymz_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "657cdafd0f4ac0961a684bcd15cbbe70bc9c563bd5b1d49c910115b18e263c23"
      url "https://github.com/yyZe0122/YunmengZe-Agent/releases/download/v#{version}/ymz_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "93d786a4a186fc7ebadadccbdac0229167d75c67a2d6f8d27207ab8137504062"
      url "https://github.com/yyZe0122/YunmengZe-Agent/releases/download/v#{version}/ymz_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ymz"
  desc "YunmengZe Agent — local-first, policy-controlled automation agent"
  homepage "https://github.com/yyZe0122/YunmengZe-Agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ymz"
  binary "ymzd"

  # No zap stanza required

end
